### ISSUE TITLE
Como interrumpir del todo la ejecución de un código

### ISSUE THREAD

**Issue by Francisco-Aguilera-xd** [IIC2233/Syllabus#106]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda

Hola!
Haciendo los ejercicios propuestos y corriendo los jupyter notebooks de esta semana, me pasaba que cuando interrumpía el kernel, o trataba de interrumpir la ejecución del código, seguía saliendo output de este, por lo tenía que esperar 30 segundos para que el código parase del todo y creo que está relacionado con los .sleeps() que habían en los códigos. ¿Hay alguna forma de interrumpir completamente la ejecución del código sin tener que esperar el output restante?

**Comment by carmebe** [comment]
Hola, en el mismo jupyter notebook se menciona que no se recomienda trabajar en ese entorno dado que sucede ese tipo de problemas, por lo que es mejor que practiques en un entorno solamente de Python.

Saludos!

**Comment by tqmbanados** [comment]
Hola @Francisco-Aguilera-xd ! Pudiste solucionar el problema? Como dicen arriba, mejor no correr código en jupyter si demorará  mucho, y en especial si en el mismo notebook recomiendan no hacerlo! Conoces el comando "Keyboard Interrupt"? En windows se hace con Ctrl + C, y su función es "matar" un problema corriendo en una terminal. Si tienes algún problema con un programa que nunca termina, puedes usar ese comando.

**Comment by Francisco-Aguilera-xd** [comment]
Siiii. ahí cache como se hacia. Muchas gracias a ambos!
