### ISSUE TITLE
Confusión sobre parametros.py en gitignore

### ISSUE THREAD

**Issue by thiaaare-sp** [IIC2233/syllabus#162]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido #54 y #161 (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía #54 y #161 (https://github.com/IIC2233/syllabus/issues/45)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, leyendo las issues para asegurarme de qué poner en el .gitignore di con la #54, la cual indica que deben ir todos los archivos *pdf, *csv y además parametros.py. Luego de esto subí mi tarea y ahora leí la issue #161 donde dice que parametros.py no va en el .gitignore y que se debe subir porque sin este mi programa no corre. Ahora tengo la duda de cómo debe ser y si efectivamente debo subirlo, cómo lo hago en git? :(

**Comment by tqmbanados** [comment]
Hola! Si modificaste el archivo para agregar más parámetros, no lo ignores, pues será necesario para correr tu programa. Si no lo modificaste, inclúyelo en el .gitignore, pues lxs ayudantes tendremos uno igual al que les entregamos.
Espero serte de ayuda!

**Comment by thiaaare-sp** [comment]
AAAA, ya muchas gracias! me volvió el alma al cuerpo 😄

**Comment by tqmbanados** [comment]
jajajaj me alegro 😊
