### ISSUE TITLE
Empate entre metros cavados y meta

### ISSUE THREAD

**Issue by pulpaulaa** [IIC2233/Syllabus#214]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/Syllabus/wiki/8.-Reglas-del-foro-(issues)).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía ([click aquí para ir al compilado](/IIC2233/syllabus/issues/127)).
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello ([click aquí para ir a esa _issue_](/IIC2233/syllabus/issues/126)).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al ayudante de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, tengo una duda acerca del caso hipotético en que al final de los días del torneo, los metros cavados por el equipo sean iguales a la meta. En el enunciado solamente dice "En caso de terminar los días se deberá mostrar el resultado de la competencia junto a los metros excavados totales y METROS_META, **indicando si ganaste o no**". Pero me queda la duda de si un empate significa que perdiste o si se debe indicar que empataste, en vez de ganar o perder.

**Comment by emolaba** [comment]
Hola @pulpaulaa ! Al no estar indicado en el enunciado queda a criterio tuyo, lo importante es que indiques en tu Readme la decisión que tomes!
Saludos!

**Comment by pulpaulaa** [comment]
@emolaba Ok, gracias! Y otra duda sobre el final del juego, si el equipo logra cavar más que la meta antes de que se terminen los días, debería terminar altiro el juego? O aún así se sigue nomás hasta el último día?

**Comment by emolaba** [comment]
@pulpaulaa Aún así se sigue hasta el último día!
