### ISSUE TITLE
FrontEnd vs Modularización

### ISSUE THREAD

**Issue by 3rdPix** [IIC2233/Syllabus#261]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Cuando se construye la interfaz gráfica, se necesita establecer un montón de configuraciones y especificar detalles geométricos, de estilo, de nombre, de contenido, etc. Esto, incrementa enormemente la cantidad de líneas necesitadas tan solo para presentar una interfaz gráfica estática (ni hablar de dinámica). Existe la posibilidad de que esta enorme cantidad de líneas de código, permanezca *oculta* en la configuración `.ui` de un archivo generado en Designer. Pero yo no utilizo tal programa! Por lo tanto, gasto una gran cantidad de líneas de código en tan solo preparar la visualización del front end, sin trabajar realmente las funcionalidades que tienen que ver con Dccruz vs zombies.

En este sentido, me preguntaba si era posible presentar en la tarea un archivo frontend que superara las 400 líneas de código. Siempre y cuando, indicara en el README esta situación, explicando **qué líneas expecíficamente** son *"lineas de relleno"*, que podrían estar implícitas en un archivo `.ui` pero que, por gusto, he decidido crear a mano. De esta forma, le indico al ayudante que esas líneas poco importan en lo que refiere a la funcionalidad del programa, son solo para ajustar la estética y que, por tanto, no necesita perder tiempo revisándolas. Y luego, si se considerara la "no existencia" de esas líneas de relleno, como si estuvieran en un archivo **.ui** (y se le resta a la cantidad de líneas de código del módulo, esas líneas de relleno), si luego de eso resulta que el programa tiene menos de 400 líneas de código de "funcionalidad", entonces lo haría "válido".

¿Se puede o tengo que rebuscar alguna forma de reducir docenas de líneas estéticas que, en otro caso, no existirían porque se podrían poner en un Designer?

**Comment by Lord-Kelsier** [comment]
Hola @3rdPix , siempre puedes usar herencia
