### ISSUE TITLE
Problema al descargar archivo en AF4

### ISSUE THREAD

**Issue by AgustinAraya** [IIC2233/Syllabus#288]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Contenido

Terminé el código de la AF4 con la información que nos daban en el cierre de la actividad y funciona bien hasta que uno selecciona un archivo para descargar, en donde se queda pegado y no realiza ninguna acción más. Dejo un screenshot de lo que me aparece en consola.

Consola servidor:

<img width="556" alt="Captura de Pantalla 2021-11-19 a la(s) 14 52 47" src="https://user-images.githubusercontent.com/89549252/142668864-fe63fa41-a70f-498d-bd86-485a2505696a.png">

Consola usuario:

<img width="1105" alt="Captura de Pantalla 2021-11-19 a la(s) 14 50 22" src="https://user-images.githubusercontent.com/89549252/142668540-212b5c5b-ed39-4ef9-9d06-26cc3ec5ca1e.png">

***Todo el código al que me refiero a continuación, estaba ya en la actividad por lo que debería ser de conocimiento público y para todos igual***

Por lo que eh logrado entender, el problema está en que en el método  `thread_recibir_input` se entra al `elif opcion == "descargar":` que desempaqueta a `self.a_descargar` el cual es un atributo vacío. Esto creo que ocurre porque se está desempaquetando el atributo `self.a_descargar` antes de que en el método `explorar_archivos`  entre a
 ```python
if descargar:
            self.a_descargar = menus.menu_descarga(recibido)
```
en donde este atributo debería tomar el valor de la opción seleccionada. Además noté que en `elif opcion == "descargar":` hay un `.wait()` sin embargo claramente no esta esperando porque ocurre lo antes mencionado. Intenté solucionarlo usando `.clear()` del evento pero no logré implementarlo y también intenté agregando un nuevo evento que se activara cuando el atributo `self.a_descargar` no fuese `None` pero tampoco me funcionó.

**¿ Alguna idea de por qué falla y posibles soluciones? ¿Es un error mío al completar la actividad o es de la actividad propiamente?**

***Gracias de antemano***

**Comment by carmebe** [comment]
Hola, primero que todo, asegúrate de tener la versión actualizada del módulo ``cliente/menus.py`` de esa actividad, dado que hubieron algunos errores que no dejaban cargar o descargar archivos. Puedes encontrarla en el mismo Syllabus.
Si eso no soluciona el problema, revisa que los *bytes* que vayas moviendo de un lado a otro se haga correctamente, siguiendo la forma en que se ha enseñado en los contenidos. Todo que esté fuera del problema de los menús debe estar relacionado a tu propio código, y para esos casos manda una respuesta aquí para ver qué sucede.

Espero que te haya servido, saludos!

**Comment by AgustinAraya** [comment]
Hola, si tengo la versión actualizada de cliente/menus.py. El tema es que no puede ser un error de mensaje porque como se puede ver en la consola del servidor, este no está recibiendo nada aún porque ocurre el error que explico en el issiue que es antes de mandar un mensaje. El error ocurre en el código que viene en la actividad (métodos que no se modificaron) y por eso quisiera saber si está bueno quizás hay otro error en la actividad.

**Comment by carmebe** [comment]
> Además noté que en `elif opcion == "descargar":` hay un `.wait()` sin embargo claramente no esta esperando porque ocurre lo antes mencionado. 

Has revisado que en el cliente, al momento de que este envié su mensaje al servidor con el método ``enviar()``, el evento ``self.evento_prints`` se reinicie? Porque eso se indicaba en el enunciado, y era importante ponerlo dado que el evento no se reiniciaba y provocaba ese error de que no espera a que el archivo a descargar llegue. Recuerda que para reiniciar un evento, se utiliza el método ``Event.clear()``

Espero que con esto se haya solucionado tu duda, saludos!

**Comment by AgustinAraya** [comment]
Hola, efectivamente no había reincido el evento =(. Ahora si descarga el archivo, pero después se queda pegado imprimiendo que "No se pudo decodificar el mensaje." Dejo screenshots de la consola.

consola servidor:
<img width="1073" alt="Captura de Pantalla 2021-11-19 a la(s) 17 11 20" src="https://user-images.githubusercontent.com/89549252/142685709-a30e1d5c-a1ea-4290-bd74-74cc1640f9ef.png">

consola cliente:
<img width="1075" alt="Captura de Pantalla 2021-11-19 a la(s) 17 11 46" src="https://user-images.githubusercontent.com/89549252/142685745-b90bd6a0-9940-499b-8a97-3eee9ee6f791.png">
<img width="1066" alt="Captura de Pantalla 2021-11-19 a la(s) 17 12 04" src="https://user-images.githubusercontent.com/89549252/142685782-ff5587ab-38d4-43c5-b5cd-02b1fcfc6cd5.png">
...

***¿Alguna idea de por qué sucede esto?***

**Comment by carmebe** [comment]
Primero, en el servidor se ve que se sigue intentado conectar/recibir un mensaje del cliente cuando este ya se desconectó, por lo que si estás usando un *loop*, debes romperlo una vez que se corte la conexión, de lo contrario te seguirá generando errores. Una vez que cierres un socket, **no puedes seguir trabajando en este**; esto lo puedes ver en la [documentación de Python](https://docs.python.org/3/library/socket.html?highlight=socket#socket.socket.close). Si el cliente está en un *loop* cuando se conecta, al desconectarse este debe romperse también.

Por otro lado, se ve que el cliente intenta decodificar un mensaje hasta cierto punto, pero luego se bloquea, esto tiene que ver con que el **servidor** no está enviando los *bytes* correctamente. Recuerda el mecanismo para enviar mensajes: primero obtener la longitud del mensaje y transformarla a *bytes*, luego codificar el mensaje a *bytes* con el método correspondiente y finalmente enviar la suma de las dos cosas. Al momento de recibirlo, se debe primero obtener la longitud y pasarla a un *int*, y luego crear un *bytearray* que vaya almacenando los *chunks* de *bytes* recibidos, hasta llegar a la longitud correspondiente.

**Comment by AgustinAraya** [comment]
Hola, logré arreglar que el servidor pare de intentar recibir mensajes del cliente cuando este ya se desconectó. Por el lado del cliente aún no puedo solucionarlo... entiendo que una vez que se cierra el socket hay que termina el loop (en este caso el método thread_escuchar()) sin embargo estuve investigando y no encontré un método para ver si el socket está conectado o no, algo así como un is_alive() de threads... ¿Sabes cómo puedo verificar esto? 

De todas formas una pregunta más general... cuando el cliente descarga un archivo, ¿la conexión debería terminar o el cliente debería poder seguir navegando? Porque no sale nada de eso en el flujo del programa en la actividad, pero por lo que estoy viendo por el código que nosotros no tuvimos que implementar funciona así.

En relación al envío de los mensajes estoy seguro que el procedimiento es correcto porque lo hizo el profe en clases.

¡Gracias por la ayuda!

**Comment by try-except** [comment]
Cuando una conección a un `socket` se corta, el método `socket.Socket.recv()` retorna un string de bytes vacío, así que podrías hacer que el cliente revise si lo que recibe está vacío o no
