### ISSUE TITLE
Duda sobre metodo de decodificación.

### ISSUE THREAD

**Issue by bernirosas** [IIC2233/Syllabus#377]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/326).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/325).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola! Me surgió una duda respecto a la decodificación de los mensajes en la tarea ya que se al codificar se pide que se ponga el número de cada bloque de 32 bytes, al decodificarlo, hay que hacer algo con estos números, o simplemente ignorarlos. Me parece que alguna vez leí que en los modelos cliente-servidor tcp, se revisa si es que llego toda la información, ¿está relacionado con eso?
Saludos y gracias.

**Comment by victoriaatria** [comment]
Hola! Perdón por la demora!
No, solo debes preocuparte de decodificar el mensaje correctamente.

Saludos y quedo atenta por si tienes más dudas :)
