### ISSUE TITLE
Error de versión y warning y todo con pyqt5

### ISSUE THREAD

**Issue by AlfonsoBadilla** [IIC2233/syllabus#432]
### Prerrequisitos

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Problema

Buenasss, reinstalé pyqt5 porque me arrojaba un error pero me sigue apareciendo (lo del WARNING: blabla) y además ahora me da el error en rojo de que las versiones no son compatibles

Adjunto imagen 👁

aiua

![Screenshot (119)](https://user-images.githubusercontent.com/80863383/117068464-4dfa1000-acf9-11eb-9a4f-dc82ac35229c.png)

**Comment by aaossa** [comment]
Hola @AlfonsoBadilla , el error parece ser porque desintalaste PyQt5 pero quedó instalado pyqt5-tools. Puedes actualizar pyqt5-tools con este comando: `pip3 install pyqt5-tools --upgrade`. En caso de no funcionar, podrías probar utilizando la URL que aparece en otra *issue* (https://github.com/IIC2233/syllabus/issues/424#issuecomment-831546959):

[https://build-system.fman.io/qt-designer-download](https://build-system.fman.io/qt-designer-download)
