### ISSUE TITLE
Los sprites de los objetos mueven todo el mapa

### ISSUE THREAD

**Issue by anibalriveros** [IIC2233/syllabus#583]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/474)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello.
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola. Lo que me pasa es que, cuando se ponen los objetos en el mapa, el mapa entero se mueve. Con esto me refiero que los obstaculos y otros objetos cambian levemente de posicion, y no entiendo porque sucede esto, ya que todos los qlabels que utilice para las grillas estan con setscaledContents (True). Cabe mencionar que cree un qGridLayout para que las grillas queden ordenadas.

**Comment by Juampisaez** [comment]
Hola @anibalriveros 
Me da la impresion a simple vista que cuando colocas un objeto en el mapa, tambien estas cambiando los objetos y obstaculos ya existentes en el mapa. Si puedes subir tu repo para ver en detalle el problema seria mas facil ayudarte.

Quedo atento :)

**Comment by anibalriveros** [comment]
Ahi te lo mande

**Comment by Juampisaez** [comment]
@anibalriveros 
Ya mira, estuve revisandolo y me di cuenta en Qt que si colocas un objeto manualmente en algun label de la grilla que creaste, se mueven los demas labels de esta grilla. Una posible solucion es no usar una grilla de este estilo por el problema que esta ocurriendo, y en su reemplazo ir creando los objetos a medida que avanza el juego (creas los objetos de forma aleatoria en el mapa y cuando pase el tiempo los borras).

Espero sea de ayuda, quedo atento si te queda alguna duda :)
