### ISSUE TITLE
Widget Padre

### ISSUE THREAD

**Issue by enriquemolinare** [IIC2233/syllabus#716]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, colocaré código simple que permita explicar mi problema o duda

### Duda
***¿A qué se refiere que un Widget sea Padre de otro Widget?***
***¿Todos los widget pueden ser padres o solo algunos?***
[Describe tu duda de manera detallada, explicando los contenidos en cuestión y ojalá colocando código o un caso de uso de ejemplo]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by aaossa** [comment]
Hola @enriquemolinare , 

En Qt todos los *widgets* deben estar contenidos dentro de otro. De hecho, se organizan en un árbol (cada *widget* puede tener 0 o varios *childs*, y cada uno también puede hacerlo) ¿Por qué? Porque esto permite tener una jerarquía, un orden, entre los elementos gráficos de la ventana. De esta manera, PyQt sabe cómo construir la ventana y a ti te da el control de tener un orden lógico entre los elementos. También hay comportamientos que se propagan, por ejemplo, cuando se destruye un *widget* se destruyen sus hijos también, y además existe el requisito de que padres e hijos deben vivir en el mismo *thread* para poder propagar estos comportamientos sin cambiar de contexto. Entonces, cuando un *widget* es padre de otro significa que le contiene y que puede controlar su ciclo de vida.

Sobre si todos los *widgets* pueden ser padres o solo algunos... todos deberían poder. Es más, es una propiedad de `QObject` (lo que mencioné arriba aparece en [esta parte de la documentación](https://doc.qt.io/qt-5/qobject.html#details)), por lo que puedes armar el árbol como quieras, con los *widgets* que ya existen, definiendo tus propias subclases, etc. Ojalá esto resuelva tu duda y, si algo no queda claro, pregunta por acá mismo ✨ ¡Éxito con la tarea!

**Comment by enriquemolinare** [comment]
ok, perfecto. Muchas gracias por la respuesta.
