### ISSUE TITLE
Redimensionar imagenes en QtDesigner

### ISSUE THREAD

**Issue by camirojasguajardo** [IIC2233/syllabus#729]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola! 
Al insertar una imagen en el label mediante pixmap -en QtDesigner-, esta queda con el tamaño original. ¿Cómo la puedo redimensionar en el mismo QtDesigner? He buscado en internet pero no he encontrado nada:(

Saludos!

**Comment by JuaniAndres** [comment]
Hola @camirojasguajardo 
Justo debajo de donde seleccionas el pixmap para la QLabel en el designer está la opción para escalar el contenido que produce el efecto que estás buscando.

**Comment by camirojasguajardo** [comment]
gracias!

**Comment by Zenos-Paradox** [comment]
Yo seleccioné esa opción, pero me sigue apareciendo el tamaño original de la imagen cada vez que modifico un parámetro de cualquier imagen. La unica solución que he encontrado es poner un tamaño máximo, para que no pase. Hay otra forma?

**Comment by JuaniAndres** [comment]
Hola @Zenos-Paradox 
Qué raro lo que te está pasando, si en designer marcaste el scaledContents de la QLabel entonces el pixmap que en este caso es la imagen se debería escalar al tamaño que tiene tu QLabel y no lo opuesto. Me puedes comentar que parámetros estas modificando y si eso lo estás haciendo en el designer o en tu código.

**Comment by Zenos-Paradox** [comment]
Lo estoy haciendo en designer y pasa cada vez que cambió, por ejemplo, el
ancho y largo desde la ventana de object properties.

**Comment by JuaniAndres** [comment]
Me parece raro lo que está pasando ya que hice unas pruebas tratando de recrear lo que me mencionas y no tuve problemas. Igual como lo pudiste arreglar especificando un tamaño máximo me quedo tranquilo. Si quieres cuando sea la sesión de ayuda para la tarea por discord puedes verlo en detalle con alguno de los ayudantes para ver qué es lo que estaba causando eso.
Éxito en la tarea y quedo atento si te sigue dando problemas :smile:

**Comment by Zenos-Paradox** [comment]
Ah me faltó mencionar que solo pasa cuando las imágenes están en un layout.

**Comment by JuaniAndres** [comment]
Perfecto ahora considerando ese detalle te entiendo perfecto. Lo que pasa es que la Qlabel en si está escalando el contenido, pero el layout modifica el tamaño de la Qlabel cuando la agregas llevando a que la imagen se vuelva a escalar a las nuevas dimensiones de la Qlabel. En parte lo que hacen los layouts es que modifican automáticamente la ubicación y el tamaño de los elementos que son parte para distribuirlos en el espacio. Tomando en cuenta eso la solución que tienes es la que encontraste que es especificar el tamaño máximo que la Qlabel se puede agrandar para que cuando pase por el layout no se le permita crecer pasado ese límite.

Espero que ahora este todo más claro.

**Comment by Zenos-Paradox** [comment]
si, gracias :)
