### ISSUE TITLE
global command

### ISSUE THREAD

**Issue by VicenteLavagnino** [IIC2233/Syllabus#76]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1).
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues/).
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/20).
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/21).
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (iic2233@ing.puc.cl).
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla.
* [X] De ser necesario, colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado una falta a la ética.

### Duda

Hola, me gustaría saber si se puede usar el comando global para variables en funciones.
Creo que puede ser un built-in prohibido pero no lo encuentro.

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by vicentethomas** [comment]
Hola! Si lo quieres usar para obtener dentro de una función una variable externa a la función (que no se entrega como parámetro ni se crea dentro de la función), entonces no está permitido ya que técnicamente esa variable es tratada como global (y están prohibidas las variables globales). 
Si es para otro tema, vuelve a preguntar en la issue #21 donde están agrupadas las librerías permitidas, prohibidas y built-ins prohibidos. Saludos!
