### ISSUE TITLE
SyntaxError en ventana hecha en Qt Designer

### ISSUE THREAD

**Issue by arielkauderer** [IIC2233/syllabus#782]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [x] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, 
Al pasar una ventana hecha en Qt Designer a python me tira un error. Traté de buscar qué podía ser, pero no encontré solución. ¿Qué podría estar pasando?
Gracias

`window_name_j, base_class_j = uic.loadUiType("Ventana Juego.ui")`

`Exception has occurred: SyntaxError
invalid syntax (<string>, line 752)
  File "/Users/arielkauderer/Desktop/arielkauderer-iic2233-2020-2/Tareas/T02/frontend.py", line 6, in <module>
    window_name_j, base_class_j = uic.loadUiType("Ventana Juego.ui")`

**Comment by knight-who-say-ni** [comment]
Hola @arielkauderer !!

De casusalidad estás corriendo tu codigo desde la terminal de tu editor de texto?? 

Si es así, prueba corriendolo desde la consola 💯.

Si el problema persiste me avisas ;)

**Comment by arielkauderer** [comment]
Hola @knight-who-say-ni!

El error que puse ahí es corriéndolo desde VS Codes.

En la terminal del computador me tira este error:

Traceback (most recent call last):
  File "frontend.py", line 16, in <module>
    window_name_j, base_class_j = uic.loadUiType("Ventana Juego.ui")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/uic/__init__.py", line 202, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "<string>", line 752
    import fotos qt_rc
                     ^
SyntaxError: invalid syntax

**Comment by knight-who-say-ni** [comment]
@arielkauderer puedes subir tus cambios actuales a tu repositorio?? Asi puedo ver en más detalle tu codigo 👌 . Y lo otro, ¿en que sistema operativo estás?

**Comment by arielkauderer** [comment]
@knight-who-say-ni 

Oka lo subo. Uso mac.

**Comment by knight-who-say-ni** [comment]
De casualidad agregaste una carpeta o archivos nuevos en la carpeta sprites/ ???

**Comment by arielkauderer** [comment]
No, no he agregado nada extra.

**Comment by knight-who-say-ni** [comment]
Cuando abres la Ventana Juego.ui, te aparece un mensaje como el siguiente??

![Captura de pantalla (1)](https://user-images.githubusercontent.com/62031388/97045731-a8493580-154c-11eb-9386-0a3b305b2061.png)

Si es así, presiona Yes. Luego, en el explorador de archivos que aparecerá, selecciona alguna carpeta y luego cancelar. Por último, guarda los cambios.

Yo hice eso y me corre, espero que te arregle el problema a ti también :) (igual estoy en windows, pero me salia el mismo error que a ti). 

Ahí me cuentas como te va 👌

**Comment by arielkauderer** [comment]
Ahí me funcionó!

Muchas gracias!!! Te pasaste

**Comment by knight-who-say-ni** [comment]
Yaaa, que bakaan  🥳 . Igual te recomiendo no poner espacios en los nombres de archivos, por lo general python no se lleva muy bien con ellos 😅.
Exito programando!!
