### ISSUE TITLE
el combo sigue si se ignora un paso?

### ISSUE THREAD

**Issue by SantinoDaloy** [IIC2233/syllabus#822]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

¿si ignoro una flecha se pierde el combo de pasos seguidos actual?

**Comment by manearaya** [comment]
Hola @SantinoDaloy!

En el enunciado se especifica que cuando se deja pasar una flecha, no se considera correcto ni incorrecto. Como el combo aumenta con un paso correcto y se elimina con un paso incorrecto, este no se ve afectado al ignorar una flecha.

Mucho éxito con la tarea!
