### ISSUE TITLE
Agregar una ventana a MainWindow (Qt Designer)

### ISSUE THREAD

**Issue by andres-tamm** [IIC2233/syllabus#839]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola!

Tengo la zona de ritmo y la tienda hechas directo en python y me gustaría agregarlas a mi MainWindow creada en Qt Designer.

En la MainWindow tengo un espacio delimitado como un widget donde quiero que aparezca la zona de ritmo y lo mismo para la tienda. Hay alguna forma de redefinir el widget de la MainWindow para que sea la zona de ritmo por ejemplo?

No encontré forma de hacerlo mediante Qt Designer y intente reescribir el método init_gui pero no puedo ver mis otras ventanas dentro de la MainWindow.

PD: En la issue (https://github.com/IIC2233/syllabus/issues/714) preguntan algo similar y eso fue lo que intenté hacer pero no me resultó y tampoco están usando Qt Designer, por eso decidí crear otra issue.

Muchas gracias! Saludos

**Comment by furcelay** [comment]
Hola @andres-tamm !

Puedes hacer algo muy similar a la issue #714, considerando que en en QtDesigner creaste una ventana que tiene una zona dada por un widget donde quieres que esté la clase `ZonaX`, digamos que a ese widget le das el nombre `contenedor_zona_x` en QtDesigner, suponiendo que quieres que quede centrada vertical y horizontalmente y sin márgenes (con eso debería quedar exactamente con la geometría que hayas definido en QtDesigner) puedes hacer algo como lo siguiente:

```python
window_name, base_class = uic.loadUiType('mi_archivo.ui')

class MainWindow(window_name, base_class):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.setupUi(self)
        
       # creamos una instancia de ZonaX contenida en el widget que queremos
        self.zona_x = ZonaX(parent=self.contenedor_zona_x, otros_argumentos)
        
        grid = QGridLayout()
        grid.setContentsMargins(QMargins(0, 0, 0, 0))
        grid.addWidget(self.zona_x)
        # lo añadimos a la region que creamos:
        self.contenedor_zona_x.setLayout(grid)
        ...


class ZonaX(QWidget)
   
    def __init__(self, parent, otros_argumentos):
        # le pasamos el parent para que sepa que ventana lo contiene    
        super().__init__(parent)
        ...
```

**Comment by andres-tamm** [comment]
Si funcionó!
Aún no se ve 100% como me gustaría pero voy a probar cambiando otras cosas en mi código.
De todas formas muchas gracias por la ayuda!
