### ISSUE TITLE
uso de sys.argv

### ISSUE THREAD

**Issue by mleon17** [IIC2233/syllabus#852]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by mleon17** [comment]
Hola, querrá saber si se permite el uso de sys.argv

**Comment by Drpinto1** [comment]
¡Hola!

Todas las preguntas sobre uso de librerías se deben hacer en la issue #699, especificando para qué quieres usarla.

¡Saludos!
