### ISSUE TITLE
FileNotFoundError al cargar archivos *.ui

### ISSUE THREAD

**Issue by LukasGuthrie** [IIC2233/syllabus#870]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Hola! Estoy teniendo problemas al importar mi plantilla de qt designer, estoy en mi archivo .py y en la misma carpeta se encuentra el archivo .ui, al hacer el `uic.loadUiType("nombre-archivo.ui")` me raisea el error `FileNotFoundError: [Errno 2] No such file or directory: "nombre-archivo.ui"` , no entiendo por qué pasa probar los ejemplos de la semana 10 no me pasó lo mismo

**Comment by JuaniAndres** [comment]
Hola @LukasGuthrie 
Podrías subir el archivo ui y tu archivo .py en donde lo estas cargando a tu repositorio para echarle una mirada

**Comment by LukasGuthrie** [comment]
ahí subi un ejemplo que no me carga

**Comment by JuaniAndres** [comment]
creo que no hiciste push porque no lo veo en tu repositorio

**Comment by LukasGuthrie** [comment]
que raro, se ve ahora? el ejemplo que hice que no funcionaba está en la carpeta del frontend, en el archivo frontend.py

**Comment by JuaniAndres** [comment]
Ya le eché una revisada y al menos el problema que me aparecía es ````UnicodeEncodeError```` que se debe a que Pyqt5 no se lleva muy bien con caracteres como la "ñ" por lo que causa que se caiga si alguna variable como por ejemplo tus señales las guardas con ñ. Entonces prueba cambiar ````señal```` por ````senal```` o otro nombre y te debería aparecer sin problemas tu ventana.
Me avisas si te funciono.

**Comment by LukasGuthrie** [comment]
que raro porque no tengo ninguna variable guardada con ñ, algunos labels de texto tenían la ñ pero al hacerle el cambio por n me sigue tirando el FileNotFound

**Comment by JuaniAndres** [comment]
Que editor de código estas ocupando y abriste en tu editor directamente la carpeta T2?
Lo otro si podrías probar correr frontend.py en consola

**Comment by JuaniAndres** [comment]
Probablemente estés ocupando visual studio en ese caso asegúrate de que la terminal de visual studio  este ubicada en el subdirectorio ````frontend```` antes de correr ````python frontend.py```` (La ubicacion actual del terminal es lo primero que te sale y si te quieres mover puedes ocupar el comando ````cd````)
Me avisas si tienes problemas o si era otro el editor que estabas ocupando.

**Comment by LukasGuthrie** [comment]
eres un crack! era porque la terminal no se encontraba en la carpeta del archivo, muchas gracias!!
