### ISSUE TITLE
Ventana de Inicio se cae al ingresar nombre no valido

### ISSUE THREAD

**Issue by dalcalde5150** [IIC2233/syllabus#905]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda
Hola, mi problema es que, al momento de apretar comenzar en la ventana de inicio, mando una señal al back end de esta para verificar si el nombre escrito es permitido, si es asi, hago otra señal que me arroja la ventana del juego sin ningun problema, sin embargo, si esto no es asi mando una señal que me muestre un QMessageBox, pero luego de cerrar este la ventana de inicio se cae y si apreto Run no pasa nada.

Hay alguna manera de solucionar esto???

**Comment by JadrinaDA** [comment]
Una QApplication por default viene configurada tal que se termine cuando cierras la última ventana esta termine de funcionar. Podría ser eso lo que causa tu error. Para arreglar esto puedes hacer qApp.setQuitOnLastWindowClosed(false) y te debería funcionar. También se pueden producir errores al intentar cerrar un QMessageBox de una forma que no sea uno de los botones que ya vienen implementados. Podrías intentar que al apretar uno QMessageBox te mande una señal que reabra la ventana de inicio antes de cerrarse para asegurarte que la aplicación no se cierre. Si sigue ocurriendo el problema te pido por favor que pushees tu código a tu repo para ver más en detalle lo que podría estar ocurriendo.
