### ISSUE TITLE
Error malloc

### ISSUE THREAD

**Issue by conyfernandezt** [IIC2233/syllabus#918]
* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)

### Duda

Hola! Hay veces que corro el codigo y me tiran errores de este tipo (hay veces que corre bien y no se cae):

"Python(14888,0x70000cca4000) malloc: Incorrect checksum for freed object 0x7f954c47fd78: probably modified after being freed.
Corrupt value: 0x7f954c479160
Python(14888,0x70000cca4000) malloc: *** set a breakpoint in malloc_error_break to debug"
"Python malloc: Double free of object 0x7f846457f190"

y despues se me cae el programa. Estaba revisando mi codigo y me di cuenta que hay una señal que se esta emitiendo constantemente dado que esta dentro de un thread y no la puedo sacar porque osino todo el juego no funciona. He tratado de buscar formas de ver como terminar el thread pero no he encontrado nada.

**Comment by aaossa** [comment]
Hola @conyfernandezt , tu error se parece mucho al que aparece en #860, donde finalmente el error se producía porque cada *thread* estaba intentando mover el elemento de la interfaz por su cuenta, en lugar de pedirle al *thread* principal que lo haga. 

En tu código veo algo similar, si es que lo entiendo bien, ya que cada `ArrowFalling` se encarga de hacer `move` sobre el `QLabel`. En su lugar, prueba haciendo que cada `QThread` envíe una señala a la ventana principal para que actualice la posición del *label* desde el *thread* principal 🤔 Por otra parte, parece que estás perdiendo la referencia al `QLabel` con cada llamada al método `new_arrow_falling`, ya que sobreescribes el atributo `self.arrow`. Para evitar esto, prueba con otro contenedor (puede ser una lista o un diccionario, depende de lo que necesites), así puedes mantener la referencia a todos los *labels* de todos los *threads* 👌 Eso explicaría el error que ves, donde te reclama que modificaste un objeto (cada *label*) que ya fue liberado de la memoria de Python (como lo sobreescribiste, Python ya no tiene acceso al `QLabel`, pero sí `Qt`). 

Ojalá te funcione eso, pero si no queda claro o no te funcion, avísa por acá mismo ✨ ¡Éxito con la tarea!

**Comment by conyfernandezt** [comment]
Hola! Lei el otro issue relacionado y se parece bastante, pero hay una cosa que no me queda del 100% claro hacer de como solucionarlo. Por lo que entiendi, lo que deberia hacer es que el thread mande una señal para que el front end sea el que se preocupe de mover la flecha. Lo otro, lo que me recomiendas es que en new_arrow_falling se genere un tipo de lista/diccionario que almacene todos los labels que se van a crear y despues esta lista se la paso al Thread?

**Comment by aaossa** [comment]
Hola @conyfernandezt , exacto 👌 En cuanto a lo de `new_arrow_falling`, me refiero a que en ese método actualices un atributo de tu ventana, para que mientras la ventana esté "viva" tus *threads* sigan siendo accesibles para Python. Lo que sucede es que Python va liberando memoria al terminar una función (si dentro de una función utilizaste una variable, cuando termina de ejecutarse ya no te sirve, solo sirve si sigues dentro de la función) por lo que en este caso es necesario mantener una referencia a ciertos objetos que creaste. Velo de esta manera: lo que tienes es una función que crea un número entre 1 y 10, y vas guardándolo en un atributo `self.numerito`. Esto te permite almacenar un valor a la vez, por lo que siempre vas "perdiendo" los valores anteriores. Lo que te sugiero es que tengas algo como `self.numeritos = list()`, de forma que cada vez que crees un número lo agregues a la lista (`self.numeritos.append(numero)`) y así no los pierdes y tu *thread* principal puede acceder a ellos y modificarlos (que es lo que te falta ahora con tus *threads*)

**Comment by aaossa** [comment]
@conyfernandezt exacto, mientras las flechas estén en un atributo de tu clase eso te debería funcionar bien 👌

**Comment by tomytable** [comment]
Hola @aaossa , tengo un error parecido ``Python(8935,0x7000080ec000) malloc: *** error for object 0x7f915cf5d230: pointer being freed was not allocated`` que aparece cuando juego en dificultad Maestro y me llama la atención porque tengo un solo thread que se encarga de recorrer mi lista de flechas y moverlas. Ojalá pueda darle una mirada para ver que está pasando. Mi archivo está en mi repositorio y hay que ejecutar el ``main.py``para correrlo.

**Comment by aaossa** [comment]
Hola @tomytable , asumiendo que lo que tienes en tu repo es lo mismo a lo que te refieres, veo un problema que podría estar relacionado. En la línea `flecha.label.move(*flecha.posicion)`, que se ejecuta desde un `Thread` (ojo, no estás usando `QThread`), estás modificando la interfaz, algo que solo debería hacer el *thread* principal. En este caso tienes que emitir una señal para que el *thread* principal haga el `*.move`. ¿Quizás sea eso? Sino, verifica también lo que comenté más arriba, asegurate de estar guardando la referencia a los *threads* y los *labels* 🤔

**Comment by tomytable** [comment]
@aaossa hola profe, acabo de actualizar mi repositorio, lo siento por la demora. En la versión anterior no lo tenía con un solo thread

**Comment by Tvergara** [comment]
Hola @aaossa ,  tengo una duda sobre el _thread principal_ que mencionas. Ese es el thread que maneja la ```MainWindow```? Y si lo es, para comunicarlo entre threads no habría que tener un ```Event``` en el _subthread_ el cual  ```MainWindow``` esté en ```wait()```? Pero eso no haría que ```MainWindow``` esté quieto y no pueda recibir otros eventos (teclas, etc)?

**Comment by aaossa** [comment]
@tomytable creo que tu método `avanzar` no funciona como esperas. Dentro del método asumes que estás moviendo a todas las flechas a la vez, mientras que fuera lo defines como si trabajara sobre solo una. Lo que estás haciendo ahora es que cada *thread* actualiza a todas las flechas 😱 Dudo que sea lo que esperas 😅 Por otra parte, quizás lo que está perdiéndose es la referencia al *thread*, podrías ver si almacenándolo en un atributo (nuevamente, como expliqué arriba) funciona como esperas

**Comment by aaossa** [comment]
@Tvergara buena pregunta, el *thread* principal es justamente el que maneja la `MainWindow`, el que se ejecuta cuando corres tu código. En el caso de eventos, eso es una posible implementación, pero tendrías que tener un *thread* aparte esperando al evento. Lo que estoy sugiriendo es que desde un *thread* emita una señal, y esa señal esté conectada en el *thread* principal a un método de tu *front-end*.
