### ISSUE TITLE
Dudas con la función para ingresar nombre

### ISSUE THREAD

**Issue by nimorales97** [IIC2233/syllabus#926]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

### Duda
Tengo dos problemas: 
1) Aún no entiendo bien cómo manejar lo que ingresa el usuario en el widget. Explicado muy a la rápida lo que intento hacer es esto: `ventana_inicio.py` llama a `validar_input(nombre)` de `funciones.py` al hacer click en comenzar, pero no entiendo aún cómo hacerlo. Podría alguien explicarme?
Edit: Me refiero a que aún no entiendo cómo hacer que lo que escribe el usuario se guarde en una variable que yo pueda procesar.

2) Me gustaría que cuando el input esté vacío salga ese típico texto en gris que a veces tienen los input en blanco que diga "solo caracteres alfanuméricos", no sé si eso tiene un nombre en específico y no he encontrado nada al respecto.

**Comment by manearaya** [comment]
Hola @nimorales97!

Asumiendo que estás usando un QLineEdit para que el usuario ingrese su nombre:

1. Te puede servir el método `text()` del label que estés usando, ya que retorna el texto que contiene el Line Edit.

2.  El método `setPlaceHolderText(...)` permite hacer lo que describes.

La información está en la documentación de [QLineEdit](https://doc.qt.io/qt-5/qlineedit.html). También te recomiendo buscar ejemplos y documentación en inglés, creo que es más probable que encuentres.

Éxito con la tarea!

**Comment by nimorales97** [comment]
@manearaya Muchas gracias!
