### ISSUE TITLE
Duda sobre baile de pinguinos y puffles

### ISSUE THREAD

**Issue by tsunayoshi21** [IIC2233/syllabus#936]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, mi duda es sobre cuando se tienen que mover los pinguinos. Si es que se mueven solo cuando hay pasos correctos? o cuando apreto cualquier tecla (WASD). 
Si lo ultimo es el caso, que hacer en caso de que si por ejemplo apreto la flecha izquierda y antes de soltarla apreto por ejemplo la de abajo. Hay que moverse desde el paso de flecha izquierda hasta el  paso izquierda-abajo? o hay que pasar por paso izquierda, neutro, paso izquierda-abajo?
Tambien siguiendo lo mismo, que hacemos cuando hay pasos de flechas como arriba-abajo o izquierda-derecha, ya que no hay sprites para esos pasos.
Graciasss de antemano, quedo atento.

**Comment by aljara97** [comment]
Hola @tsunayoshi21, los pinguirines solo se moverán cuando el paso realizado es correcto 🐧

**Comment by tsunayoshi21** [comment]
Tambien siguiendo lo mismo, que hacemos cuando hay pasos de flechas como arriba-abajo o izquierda-derecha, ya que no hay sprites para esos pasos.
Graciasss de antemano, quedo atento.

**Comment by aljara97** [comment]
Hola, con respecto al uso de sprites para esos pasos te recomiendo ver la issue #786, espero sea de ayuda.

Mucha suerte

**Comment by jorgetf-desing** [comment]
> Hola @tsunayoshi21, los pinguirines solo se moverán cuando el paso realizado es correcto 🐧

Hola, en el enunciado dice cada vez que hace un paso nuevo.. en mi caso lo interprete como un paso correcto o incorrecto ya que eso no se especifica bien
