### ISSUE TITLE
Duda creacion de clases (Qlabel) en front y back end

### ISSUE THREAD

**Issue by tsunayoshi21** [IIC2233/syllabus#947]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

Hola, 
Para hacer mi programa, en una parte creo la clase pinguino que hereda de Qlabel y luego los instancia en la ventana de juego del front-end. La creación de clases, lo hice en un modulo distinto. Mi duda es si es que este modulo correspondería más a front o back end.
Gracias

**Comment by kadroguett** [comment]
Hola @tsunayoshi21, recuerda que el front-end se encarga de la parte gráfica del programa mientras que el back-end se encarga de la lógica. En este caso estás creando los labels que corresponden a elementos gráficos, por lo que corresponderían al front-end.
