### ISSUE TITLE
si uso código de la carpeta contenidos de IIC2233, debo citarlo?

### ISSUE THREAD

**Issue by notyourlasagna** [IIC2233/syllabus#957]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
*X ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

Si adapto parte del código de uno de los archivos del repositorio contenidos del curso, debo citarlo en mi readme?

**Comment by aljara97** [comment]
Hola @notyourlasagna, si es que adaptas el código al contexto de tu programa y no lo copias literalmente no habría problema si no lo citas. En cambio, en cambio si incluyes una funcionalidad tal cual está implementada debes citarla en tu readme. Sin embargo, te recomiendo en el primer caso igual indicar en tu readme que te inspiraste en cierta funcionalidad implementada en los contenidos del curso para que el o la ayudante que corrija tu tarea tenga conocimiento de esto.

Espero haber aclarado tu duda 🐧
