### ISSUE TITLE
Qobject has no attribute emit

### ISSUE THREAD

**Issue by alanpiket** [IIC2233/syllabus#960]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [x] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [x] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [x] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [x] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [x] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [x] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

### Duda

[Describe tu duda de manera detallada, explicando qué cosas aparecen en el enunciado y cuáles no]
[**
<img width="1136" alt="Captura de Pantalla 2020-10-30 a la(s) 5 46 07 p  m" src="https://user-images.githubusercontent.com/69634748/97755626-4e121c80-1ad8-11eb-8026-7142329ccefd.png">
![Uploading Captura de Pantalla 2020-10-30 a la(s) 5.46.02 p. m..png…]()

Hola, al definir la señal senal_flecha_creada, instanciarlas propiamente y definirlas no se por que me arroja el siguiente error.

Sin poder arreglar esto mi código dejó de funcionar, por lo que si me pudieran ayudar sería genial. Muchas gracias **]

[De ser necesario, coloca tu pregunta de manera explícita utilizando **este formato**]

**Comment by manearaya** [comment]
Hola @alanpiket!

Lo más probable es que en alguna parte de tu código estés usando `emit()` con una clase que no es un `pyqtSignal()`, y por eso te aparece ese error. Si no encuentras el error, puedes hacer push a tu repositorio para ayudarte a encontrarlo.

**Comment by alanpiket** [comment]
Estoy casi seguro de que si son pyqtsignals, haré un push ahora a ver si me puedes ayudar porfa

**Comment by alanpiket** [comment]
ya hice el push a ver si me pueden ayudar

**Comment by manearaya** [comment]
Creo que encontré el problema! 

En el archivo `punt_pros.py`, cuando instancias a la clase `Procesador_Puntos()`, te faltan los paréntesis 😅 (en la línea 84 en lugar de ser `punt_pros = Procesador_Puntos()` es `punt_pros = Procesador_Puntos`)

Avísame si te funciona ahora!
