### ISSUE TITLE
Qthread destroyed while running

### ISSUE THREAD

**Issue by JDomingoSilva** [IIC2233/syllabus#962]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [X] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [X] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola, he visto que a muchos les ha salido este problema de destroyed while running, y ya vi todas esas issues para tratar de resolver mi problema pero no encontre nada que me sirva... los threads si los voy guardando en una lista por ejemplo.
Hay muchas veces que puedo terminar un nivel sin problema, es solo de repente que se crashea y tira el error de destroyed while running. Por favor alguien que le pueda echar un ojo a mi código que estoy super atrasado. Gracias por adelantado

**Comment by juanpaxd** [comment]
A mi me sucede lo mismo, hay veces que los niveles son completados, pero otras veces se cierra. Pero a mi no me sale ningun error, solo se queda pegado y despues de un rato, se cierra.

**Comment by kadroguett** [comment]
Hola @JDomingoSilva, probé tu código y en efecto se me caía a veces cuando jugaba. Luego intenté modificando el archivo `backend.py` de la siguiente manera:

![image](https://user-images.githubusercontent.com/31357861/97765861-ae15bc80-1af2-11eb-9c01-fefbbec2bee1.png)

![image](https://user-images.githubusercontent.com/31357861/97765870-bc63d880-1af2-11eb-8679-ad557f35ef37.png)

Siguiendo el fundamento de la issue #940 y el problema se solucionó. Intenta haciendo lo mismo y prueba a ver si se te sigue cayendo y me cuentas como te va.

**Comment by JDomingoSilva** [comment]
Perdón no haber leido tu respuesta, estaba super concentrado en seguir avanzando jajaja. Efectivamente me funcionó!, no se me ha caido en las pruebas que llevo hasta ahora, muchas gracias!

**Comment by kadroguett** [comment]
No te preocupes, que bueno que te funcionó. Éxito en tu tarea!! 😺
