### ISSUE TITLE
Problema al capturar flechas por cercanía.

### ISSUE THREAD

**Issue by pablomaizag** [IIC2233/syllabus#977]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [ ] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [ ] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [ ] Revisé el compilado de dudas de la tarea y no encontré una *issue* similar a la mía (https://github.com/IIC2233/syllabus/issues/700)
* [ ] Mi duda no se trata sobre una librería, *built-in* o mala práctica, ya que eso se pregunta en la *issue* creada para ello (https://github.com/IIC2233/syllabus/issues/699)
* [ ] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [ ] Utilizaré un título descriptivo y llenaré correctamente esta plantilla
* [ ] De ser necesario, solo colocaré código simple que permita explicar mi problema o duda, ya que compartir código de esta evaluación puede ser considerado copia

Hola! Al momento de capturar flechas en modo "Maestro Cumbia", estas salen cada muy poco tiempo por lo que vienen muy cerca una de la otra, esto genera que si vienen 2 correspondientes a la misma tecla y la presiono en el momento en que ambas están tocando al menos un pixel del cuadrado correspondiente a la tecla, desaparecen las 2 juntas con tan solo un toque, ¿puede pasar esto?¿ lo especifico en el ReadMe ?

**Comment by knight-who-say-ni** [comment]
Holaa @pablomaizag !!

Para este caso, corre lo mismo que lo descrito en la issue #845.

Saludos y exito con la tarea!!
