### ISSUE TITLE
AYUDA borre todo mi progreso localmente sin querer de github

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2233/syllabus#992]
### Prerrequisitos
(Marcar colocando una X entre los corchetes los ítems que ya hiciste, así: "[X]")

* [X] Leí las reglas del foro (https://github.com/IIC2233/syllabus/issues/1)
* [X] Busqué en las *issues* si ya preguntaron mi duda y no encontré nada parecido (https://github.com/IIC2233/syllabus/issues)
* [X] Mi duda no se trata de un tema administrativo o personal, ya que en ese caso debo contactar a mi profe, al Jefe de Bienestar o al correo del curso (https://iic2233.github.io/contacto/)
* [X] Utilizaré un título descriptivo y llenaré correctamente esta plantilla

Hola, necesito ayuda, usé este link: https://www.campusmvp.es/recursos/post/como-eliminar-el-ultimo-commit-de-git-en-el-repositorio-de-origen-p-ej-github.aspx
porque queria borrar todo mi ultimo commit (sin querer habia subido ranking.txt)

Termine borrando todo mi avance desde el commit inicial localmente también. que puedo hacer??

GRACIAS.

**Comment by aaossa** [comment]
Hola @pabloalvarez67 , vamos por partes. ¿Puedes mostrarme el output del siguiente comando en tu repositorio local:  `git reflog?` No cierres la consola (por si acaso) Otra pregunta, ¿hiciste *commits* que no alcanzaste a subir o solo tenías ese *commit *y borraste lo demás?

**Comment by aaossa** [comment]
También `git status` plis

**Comment by pabloalvarez67** [comment]
![Captura de Pantalla 2020-10-31 a la(s) 4 49 13 p  m](https://user-images.githubusercontent.com/62023649/97788612-07d0c200-1b99-11eb-8291-a8c6e5cc47a3.png)
@aaossa 
Ahi esta el pantallazo.
primero habia hecho git add de toda mi tarea.
Luego use eso que encontre en internet para borrar ese commit (y así subirlo denuevo borrando ranking.txt)
Pero termine borrando todo mi avance desde el commit inicial (unas pocas lineas y el git ignore)
Lo malo es que localmente tambien perdí mi progreso, me faltan archivos que habia creado y los que ya habia creado perdieron casi todo lo que tenia antes.

**Comment by aaossa** [comment]
@pabloalvarez67 , no veo el *output* de `git reflog` ni de `git status` 😅 ¿Podrías correr esos comandos y mostrarme lo que ves?

**Comment by pabloalvarez67** [comment]
@aaossa  el git reflog es larguisimo, te lo mando igual??

**Comment by aaossa** [comment]
@pabloalvarez67 me interesan las primeras 3-5 líneas al menos, el resto no debería ser necesario

**Comment by pabloalvarez67** [comment]
![Captura de Pantalla 2020-10-31 a la(s) 4 58 22 p  m](https://user-images.githubusercontent.com/62023649/97788792-4fa41900-1b9a-11eb-8f96-1d61e83691a7.png)
ese "quizas ultimo commit" fue lo ultimo que subi

**Comment by aaossa** [comment]
Mmm estoy algo confundido, porque tu último *commit* en GitHub es de hace 7 días. Hagamos esto, ya que estoy entre 2 posibles soluciones, vamos con el primer paso de ambas:

1. Copia tu repo, por si acaso (copia toda la carpeta, no cada uno de los contenidos, solo copia y pega la carpeta en otro lado)
2. (Posible solución 1, como respaldo) Ahora, en tu repo local corre este comando: `git fsck --lost-found`, que (en simple) va a ver cuáles archivos que git alguna vez vió (porque les hiciste `git add`) ya no existen y los va a respaldar en una carpeta
3. (Posible solución 2, que podría funcionar directamente) Corre el comando `git reset --hard fe12add`, que debería cambiar los contenidos de tu repo local a los que estaban en el *commit* "quizas ultimo commit"

Por favor no te saltes ningún paso (el primero es el más importante), y muestrame el output del comando del paso 2 y del comando del paso 3. También, cuando corras el comando del paso 3, revisa si los contenidos de tu carpeta están bien (y si funciona, por favor no corras otro comando, avísame y te ayudo). Ojalá funcione 🤞

**Comment by pabloalvarez67** [comment]
![Captura de Pantalla 2020-10-31 a la(s) 5 12 46 p  m](https://user-images.githubusercontent.com/62023649/97789073-56cc2680-1b9c-11eb-8e12-10993d1be5dd.png)

Funcionó!! recupere localmente todos mis archivos.
ahora realizare localmente ese pequeño cambio y subiré la tarea.

Espero repuesta por si acaso debo hacer algo más (?

Muchas gracias @aaossa

**Comment by aaossa** [comment]
@pabloalvarez67 que bien que recuperaste tu código 🤩 Lo que te recomiendo es hacer `git push` al tiro 😅 Luego, haz un nuevo *commit* quitando el archivo, el resultado neto es el mismo (no estará el archivo a la hora de recolectar). Es más simple hacer eso (simple en el sentido de que ocurren menos infartos). 

Y por favor, haz *commit* y *push* más frecuentemente 👀 

---

**Lección por si alguien más ve esta *issue*:** Los comandos con `--hard` modifican los archivos localmente, por lo que causan la pérdida irreversible (en general) de los cambios que no hayan sido guardados. En este caso, los contenidos se salvaron solo porque había un *commit* previo, pero si no hubiese un *commit*... no habría tarea 😅
